{
 "title": "Logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "query" }
  ]
 },
 "panels": [
  {
   "title": "Driver Log(STD out)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"driver-stdout\"} |= `$query`"
    }
   ]
  },
  {
   "title": "Driver Log(STD err)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"driver-stderr\"} |= `$query`"
    }
   ]
  },
  {
   "title": "Worker1 Log(STD out)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"worker1-stdout\"} |= `$query`"
    }
   ]
  },
  {
   "title": "Worker1 Log(STD err)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"worker1-stderr\"} |= `$query`"
    }
   ]
  },
  {
   "title": "Worker 2 Log(STD out)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"worker2-stdout\"} |= `$query`"
    }
   ]
  },
  {
   "title": "Worker 2 Log(STD err)",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"worker2-stderr\"} |= `$query`"
    }
   ]
  },
  {
   "title": "Worker 3 Log(STD out)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"worker3-stdout\"} |= `$query`"
    }
   ]
  },
  {
   "title": "Worker 3 Log(STD err)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "{job=\"worker3-stderr\"} |= `$query`"
    }
   ]
  }
 ]
}