create table log_table(
  sentence text
);

create table product(
  id serial primary key,
  price int not null, -- 상품 가격 
  seller int not null, -- 판매자 아이디 
  name varchar(100) not null, -- 상품명 
  num_stock int not null -- 상품 재고 수
);

insert into product(price, seller, name, num_stock) values (10000, 1, 'A사 친환경 테이블', 100), (20000, 1, 'B사 접이식 캠핑 테이블', 100), (500000, 2, 'C사 안마의자', 5),
	(5000, 3, 'D사 무공해 랩', 1000), (5000, 3, 'E사 샤워헤드', 1000), (70000, 4, 'E사 에어프라이어', 50), (1000000, 4, 'F사 폴더블 스마트폰', 10), 
	(800000, 5, 'G사 52인치 OLED TV', 10);

create table seller(
  id serial primary key,
  name varchar(100) not null  -- 판매자명 
);

insert into seller(name) values ('가구 왕국'), ('안마의자 도매상사'), ('다이쓔'), ('헬로마트'), ('올굿프라자');


create table ordered(
  id serial primary key,
  product_id int not null,  -- 상품 아이디
  amount int not null,  -- 주문 상품 갯수
  order_date timestamp not null  -- 주문일자
);
insert into ordered(product_id, amount, order_date) values (1, 3, '2023-10-01 10:30:12'), (1, 10, '2023-10-03 10:30:12'), (1, 1, '2023-10-05 10:30:12'),
	(2, 10, '2023-10-02 02:00:57'), (2, 1, '2023-10-03 05:33:22'), (2, 1, '2023-10-04 17:33:55'),
	(3, 1, '2023-10-01 19:00:11'), (2, 1, '2023-10-03 06:23:11'), (2, 5, '2023-10-04 08:23:51'),
	(6, 1, '2023-10-03 23:15:27'), (6, 3, '2023-10-05 22:12:37'), (6, 2, '2023-10-01 00:12:15'), 
	(6, 3, '2023-10-02 09:11:51'), (6, 9, '2023-10-04 05:22:59'),
	(3, 1, '2023-10-01 19:00:11'), (2, 1, '2023-10-03 06:23:11'), (2, 5, '2023-10-04 08:23:51');

create table covid(
  id serial primary key,
  datadate timestamp,  
  country varchar(100), 
  new_cases int,
  new_deaths int,
  total_cases int,
  total_deaths int
);

INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Spain', 615, 8, 1639, 36);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Spain', 501, 12, 2140, 48);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Spain', 825, 36, 2965, 84);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Spain', 1266, 36, 4231, 120);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Spain', 1522, 16, 5753, 136);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Spain', 2000, 152, 7753, 288);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Spain', 1438, 21, 9191, 309);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-28', 'Sri Lanka', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-29', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-30', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-31', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-01', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-02', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-03', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-04', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-05', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-06', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-07', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-08', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-09', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-10', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-11', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-12', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-13', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-14', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-15', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-16', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-17', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-18', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-19', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-20', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-21', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-22', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-23', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-24', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-25', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Sri Lanka', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Sri Lanka', 1, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Sri Lanka', 1, NULL, 3, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Sri Lanka', 3, NULL, 6, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Sri Lanka', 5, NULL, 11, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Sri Lanka', 8, NULL, 19, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Sri Lanka', 10, NULL, 29, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Sudan', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Sudan', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Sudan', 0, NULL, 1, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Sudan', 1, 0, 2, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Suriname', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Suriname', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-01', 'Sweden', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-02', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-03', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-04', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-05', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-06', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-07', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-08', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-09', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-10', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-11', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-12', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-13', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-14', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-15', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-16', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-17', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-18', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-19', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-20', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-21', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-22', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-23', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-24', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-25', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'Sweden', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'Sweden', 1, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'Sweden', 5, NULL, 7, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'Sweden', 5, NULL, 12, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'Sweden', 1, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'Sweden', 1, NULL, 14, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'Sweden', 1, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'Sweden', 9, NULL, 24, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'Sweden', 11, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'Sweden', 26, NULL, 61, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'Sweden', 76, NULL, 137, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'Sweden', 24, NULL, 161, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'Sweden', 42, NULL, 203, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'Sweden', 45, NULL, 248, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Sweden', 78, NULL, 326, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Sweden', 135, NULL, 461, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Sweden', 159, NULL, 620, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Sweden', 155, NULL, 775, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Sweden', 149, NULL, 924, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Sweden', 68, NULL, 992, 3);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Sweden', 67, 0, 1059, 3);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'Switzerland', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'Switzerland', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'Switzerland', 5, NULL, 6, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'Switzerland', 4, NULL, 10, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'Switzerland', 8, NULL, 18, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'Switzerland', 6, NULL, 24, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'Switzerland', 6, NULL, 30, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'Switzerland', 7, NULL, 37, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'Switzerland', 19, NULL, 56, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'Switzerland', 30, NULL, 86, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'Switzerland', 123, 0, 209, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'Switzerland', 55, 1, 264, 2);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'Switzerland', 68, 0, 332, 2);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'Switzerland', 0, 0, 332, 2);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Switzerland', 159, 1, 491, 3);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Switzerland', 154, 1, 645, 4);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Switzerland', 213, 2, 858, 6);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Switzerland', 267, 0, 1125, 6);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Switzerland', 234, 5, 1359, 11);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Switzerland', 841, 2, 2200, 13);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Switzerland', 0, 1, 2200, 14);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-21', 'Thailand', NULL, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-22', 'Thailand', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-23', 'Thailand', 2, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-24', 'Thailand', 0, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-25', 'Thailand', 0, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-26', 'Thailand', 1, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-27', 'Thailand', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-28', 'Thailand', 9, NULL, 14, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-29', 'Thailand', 0, NULL, 14, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-30', 'Thailand', 0, NULL, 14, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-31', 'Thailand', 0, NULL, 14, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-01', 'Thailand', 5, NULL, 19, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-02', 'Thailand', 0, NULL, 19, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-03', 'Thailand', 0, NULL, 19, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-04', 'Thailand', 0, NULL, 19, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-05', 'Thailand', 6, NULL, 25, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-06', 'Thailand', 0, NULL, 25, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-07', 'Thailand', 0, NULL, 25, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-08', 'Thailand', 7, NULL, 32, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-09', 'Thailand', 0, NULL, 32, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-10', 'Thailand', 0, NULL, 32, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-11', 'Thailand', 1, NULL, 33, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-12', 'Thailand', 0, NULL, 33, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-13', 'Thailand', 0, NULL, 33, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-14', 'Thailand', 0, NULL, 33, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-15', 'Thailand', 1, NULL, 34, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-16', 'Thailand', 0, NULL, 34, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-17', 'Thailand', 1, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-18', 'Thailand', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-19', 'Thailand', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-20', 'Thailand', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-21', 'Thailand', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-22', 'Thailand', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-23', 'Thailand', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-24', 'Thailand', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-25', 'Thailand', 2, NULL, 37, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'Thailand', 3, NULL, 40, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'Thailand', 0, NULL, 40, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'Thailand', 0, NULL, 40, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'Thailand', 2, NULL, 42, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'Thailand', 0, NULL, 42, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'Thailand', 0, NULL, 42, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'Thailand', 1, 0, 43, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'Thailand', 0, 0, 43, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'Thailand', 4, 0, 47, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'Thailand', 0, 0, 47, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'Thailand', 1, 0, 48, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'Thailand', 2, 0, 50, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'Thailand', 0, 0, 50, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'Thailand', 3, 0, 53, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Thailand', 6, 0, 59, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Thailand', 11, 0, 70, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Thailand', 5, 0, 75, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Thailand', 0, 0, 75, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Thailand', 0, 0, 75, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Thailand', 39, 0, 114, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Thailand', 33, 0, 147, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-01', 'United Kingdom', NULL, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-02', 'United Kingdom', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-03', 'United Kingdom', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-04', 'United Kingdom', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-05', 'United Kingdom', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-06', 'United Kingdom', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-07', 'United Kingdom', 1, NULL, 3, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-08', 'United Kingdom', 0, NULL, 3, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-09', 'United Kingdom', 0, NULL, 3, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-10', 'United Kingdom', 1, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-11', 'United Kingdom', 4, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-12', 'United Kingdom', 0, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-13', 'United Kingdom', 1, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-14', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-15', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-16', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-17', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-18', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-19', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-20', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-21', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-22', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-23', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-24', 'United Kingdom', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-25', 'United Kingdom', 4, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'United Kingdom', 0, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'United Kingdom', 0, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'United Kingdom', 3, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'United Kingdom', 4, NULL, 20, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'United Kingdom', 3, NULL, 23, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'United Kingdom', 13, NULL, 36, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'United Kingdom', 3, NULL, 39, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'United Kingdom', 12, NULL, 51, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'United Kingdom', 38, NULL, 89, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'United Kingdom', 29, NULL, 118, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'United Kingdom', 49, NULL, 167, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'United Kingdom', 43, 1, 210, 2);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'United Kingdom', 67, 0, 277, 2);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'United Kingdom', 46, 1, 323, 3);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'United Kingdom', 50, 3, 373, 6);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'United Kingdom', 87, 0, 460, 6);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'United Kingdom', 134, 2, 594, 8);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'United Kingdom', 208, 2, 802, 10);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'United Kingdom', 342, 11, 1144, 21);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'United Kingdom', 251, 14, 1395, 35);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'United Kingdom', 152, 20, 1547, 55);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'Togo', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Togo', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Trinidad and Tobago', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Trinidad and Tobago', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Trinidad and Tobago', 1, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Trinidad and Tobago', 3, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'Tunisia', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'Tunisia', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'Tunisia', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'Tunisia', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'Tunisia', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'Tunisia', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'Tunisia', 1, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'Tunisia', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Tunisia', 4, NULL, 6, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Tunisia', 0, NULL, 6, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Tunisia', 1, NULL, 7, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Tunisia', 9, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Tunisia', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Tunisia', 2, NULL, 18, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Tunisia', 2, NULL, 20, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Turkey', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Turkey', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Turkey', 4, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Turkey', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Turkey', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Turkey', 42, NULL, 47, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'Ukraine', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'Ukraine', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'Ukraine', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'Ukraine', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'Ukraine', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'Ukraine', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'Ukraine', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Ukraine', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Ukraine', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Ukraine', 2, NULL, 3, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Ukraine', 0, NULL, 3, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Ukraine', 0, 0, 3, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Ukraine', 0, 0, 3, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Ukraine', 4, 0, 7, 1);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-29', 'United Arab Emirates', NULL, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-30', 'United Arab Emirates', 0, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-31', 'United Arab Emirates', 0, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-01', 'United Arab Emirates', 0, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-02', 'United Arab Emirates', 1, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-03', 'United Arab Emirates', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-04', 'United Arab Emirates', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-05', 'United Arab Emirates', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-06', 'United Arab Emirates', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-07', 'United Arab Emirates', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-08', 'United Arab Emirates', 2, NULL, 7, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-09', 'United Arab Emirates', 0, NULL, 7, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-10', 'United Arab Emirates', 0, NULL, 7, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-11', 'United Arab Emirates', 1, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-12', 'United Arab Emirates', 0, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-13', 'United Arab Emirates', 0, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-14', 'United Arab Emirates', 0, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-15', 'United Arab Emirates', 0, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-16', 'United Arab Emirates', 0, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-17', 'United Arab Emirates', 1, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-18', 'United Arab Emirates', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-19', 'United Arab Emirates', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-20', 'United Arab Emirates', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-21', 'United Arab Emirates', 0, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-22', 'United Arab Emirates', 2, NULL, 11, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-23', 'United Arab Emirates', 2, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-24', 'United Arab Emirates', 0, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-25', 'United Arab Emirates', 0, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'United Arab Emirates', 0, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'United Arab Emirates', 0, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'United Arab Emirates', 6, NULL, 19, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'United Arab Emirates', 0, NULL, 19, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'United Arab Emirates', 0, NULL, 19, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'United Arab Emirates', 2, NULL, 21, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'United Arab Emirates', 0, NULL, 21, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'United Arab Emirates', 6, NULL, 27, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'United Arab Emirates', 0, NULL, 27, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'United Arab Emirates', 0, NULL, 27, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'United Arab Emirates', 18, NULL, 45, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'United Arab Emirates', 0, NULL, 45, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'United Arab Emirates', 0, NULL, 45, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'United Arab Emirates', 14, NULL, 59, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'United Arab Emirates', 15, NULL, 74, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'United Arab Emirates', 0, NULL, 74, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'United Arab Emirates', 11, NULL, 85, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'United Arab Emirates', 0, NULL, 85, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'United Arab Emirates', 0, NULL, 85, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'United Arab Emirates', 13, NULL, 98, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'United Arab Emirates', 0, NULL, 98, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Tanzania', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'United States Virgin Islands', NULL, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-23', 'United States', NULL, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-24', 'United States', 0, NULL, 1, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-25', 'United States', 1, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-26', 'United States', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-27', 'United States', 3, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-28', 'United States', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-29', 'United States', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-30', 'United States', 0, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-31', 'United States', 1, NULL, 6, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-01', 'United States', 1, NULL, 7, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-02', 'United States', 1, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-03', 'United States', 3, NULL, 11, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-04', 'United States', 0, NULL, 11, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-05', 'United States', 0, NULL, 11, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-06', 'United States', 1, NULL, 12, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-07', 'United States', 0, NULL, 12, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-08', 'United States', 0, NULL, 12, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-09', 'United States', 0, NULL, 12, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-10', 'United States', 0, NULL, 12, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-11', 'United States', 1, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-12', 'United States', 0, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-13', 'United States', 1, NULL, 14, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-14', 'United States', 1, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-15', 'United States', 0, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-16', 'United States', 0, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-17', 'United States', 0, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-18', 'United States', 0, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-19', 'United States', 0, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-20', 'United States', 0, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-21', 'United States', 0, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-22', 'United States', 20, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-23', 'United States', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-24', 'United States', 0, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-25', 'United States', 18, NULL, 53, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'United States', 0, NULL, 53, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'United States', 6, NULL, 59, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'United States', 0, NULL, 59, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'United States', 3, NULL, 62, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'United States', 0, NULL, 62, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'United States', 0, NULL, 62, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'United States', 2, NULL, 64, 2);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'United States', 44, 4, 108, 6);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'United States', 21, 3, 129, 9);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'United States', 19, 1, 148, 10);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'United States', 65, 1, 213, 11);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'United States', 0, 0, 213, 11);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'United States', 0, 0, 213, 11);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'United States', 259, 8, 472, 19);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'United States', 224, 6, 696, 25);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'United States', 291, 4, 987, 29);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'United States', 277, 7, 1264, 36);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'United States', 414, 5, 1678, 41);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'United States', 0, 0, 1678, 41);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'United States', 0, 0, 1678, 41);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'United States', 1825, 17, 3503, 58);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Uruguay', NULL, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Uruguay', 2, NULL, 6, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Uzbekistan', NULL, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Uzbekistan', 0, NULL, 4, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Venezuela', NULL, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Venezuela', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Venezuela', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Venezuela', 31, NULL, 33, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-24', 'Vietnam', NULL, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-25', 'Vietnam', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-26', 'Vietnam', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-27', 'Vietnam', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-28', 'Vietnam', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-29', 'Vietnam', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-30', 'Vietnam', 0, NULL, 2, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-31', 'Vietnam', 3, NULL, 5, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-01', 'Vietnam', 1, NULL, 6, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-02', 'Vietnam', 1, NULL, 7, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-03', 'Vietnam', 1, NULL, 8, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-04', 'Vietnam', 1, NULL, 9, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-05', 'Vietnam', 1, NULL, 10, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-06', 'Vietnam', 0, NULL, 10, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-07', 'Vietnam', 2, NULL, 12, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-08', 'Vietnam', 1, NULL, 13, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-09', 'Vietnam', 1, NULL, 14, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-10', 'Vietnam', 0, NULL, 14, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-11', 'Vietnam', 1, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-12', 'Vietnam', 0, NULL, 15, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-13', 'Vietnam', 1, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-14', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-15', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-16', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-17', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-18', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-19', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-20', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-21', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-22', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-23', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-24', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-25', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'Vietnam', 0, NULL, 16, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'Vietnam', 1, NULL, 17, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'Vietnam', 4, NULL, 21, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'Vietnam', 9, NULL, 30, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'Vietnam', 1, NULL, 31, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'Vietnam', 4, NULL, 35, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'Vietnam', 4, NULL, 39, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'Vietnam', 0, NULL, 39, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'Vietnam', 9, NULL, 48, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'Vietnam', 5, NULL, 53, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'Vietnam', 4, NULL, 57, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'Vietnam', 4, NULL, 61, NULL);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-21', 'World', 0, 0, 282, 6);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-22', 'World', 32, 0, 314, 6);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-23', 'World', 266, 11, 581, 17);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-24', 'World', 262, 8, 846, 25);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-25', 'World', 467, 16, 1320, 41);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-26', 'World', 691, 15, 2014, 56);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-27', 'World', 783, 24, 2798, 80);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-28', 'World', 1792, 26, 4593, 106);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-29', 'World', 1468, 26, 6065, 132);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-30', 'World', 1750, 38, 7818, 170);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-01-31', 'World', 2006, 43, 9826, 213);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-01', 'World', 2121, 46, 11953, 259);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-02', 'World', 2604, 45, 14557, 305);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-03', 'World', 2834, 57, 17391, 362);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-04', 'World', 3239, 64, 20630, 426);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-05', 'World', 3913, 66, 24544, 492);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-06', 'World', 3712, 73, 28276, 565);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-07', 'World', 3205, 73, 31481, 638);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-08', 'World', 3405, 86, 34886, 724);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-09', 'World', 2672, 89, 37558, 813);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-10', 'World', 2996, 97, 40554, 910);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-11', 'World', 2549, 108, 43103, 1018);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-12', 'World', 2068, 97, 45171, 1115);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-13', 'World', 1826, 254, 46997, 1369);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-14', 'World', 2056, 13, 49053, 1383);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-15', 'World', 1526, 143, 50580, 1526);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-16', 'World', 1277, 142, 51857, 1669);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-17', 'World', 19572, 106, 71429, 1775);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-18', 'World', 1903, 98, 73332, 1873);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-19', 'World', 1872, 136, 75204, 2009);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-20', 'World', 542, 115, 75748, 2129);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-21', 'World', 1021, 118, 76769, 2247);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-22', 'World', 1023, 112, 77794, 2359);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-23', 'World', 1017, 102, 78811, 2463);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-24', 'World', 517, 155, 79331, 2618);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-25', 'World', 896, 82, 80239, 2700);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-26', 'World', 864, 62, 81109, 2762);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-27', 'World', 1175, 42, 82294, 2804);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-28', 'World', 1353, 54, 83652, 2858);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-02-29', 'World', 1748, 66, 85403, 2924);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-01', 'World', 1727, 53, 87137, 2977);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-02', 'World', 1801, 64, 88948, 3043);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-03', 'World', 1912, 67, 90869, 3112);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-04', 'World', 2217, 86, 93090, 3198);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-05', 'World', 2220, 79, 95324, 3280);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-06', 'World', 2864, 99, 98192, 3380);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-07', 'World', 3730, 104, 101927, 3486);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-08', 'World', 3644, 96, 105592, 3584);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-09', 'World', 3979, 224, 109577, 3809);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-10', 'World', 4119, 201, 113702, 4012);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-11', 'World', 4611, 275, 118319, 4292);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-12', 'World', 6936, 317, 125260, 4613);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-13', 'World', 7488, 338, 132758, 4956);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-14', 'World', 9761, 433, 142534, 5392);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-15', 'World', 10967, 343, 153517, 5735);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-16', 'World', 13971, 855, 167506, 6606);
INSERT INTO covid(datadate, country, new_cases, new_deaths, total_cases, total_deaths) VALUES ('2020-03-17', 'World', 11594, 819, 179112, 7426);